### ISSUE TITLE
What is the schema code of the model?

### ISSUE THREAD

**Issue by wenyuhaokikika** [KCLabMTU/LMSuccSite#1]
What is the schema code of the model?

**Comment by wenyuhaokikika** [comment]
only model file but not model code，please provide~~~

**Comment by suresh-pokharel** [comment]
You can find most of the training code in [training codes](https://github.com/KCLabMTU/LMSuccSite/tree/main/training%20codes) folder.

**Comment by wenyuhaokikika** [comment]
ook thank you ~~~
